# Generated by Django 4.2 on 2026-04-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
