# Generated by Django 4.2 on 2026-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_offer_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
