# Generated by Django 4.2 on 2026-04-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_publicreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='publicreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile'),
        ),
        migrations.AlterField(
            model_name='publicreview',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
